spring.application.name=pulsetrade-user-service

spring.datasource.url:jdbc:postgresql://localhost:5432/userDatabase
spring.datasource.username:postgres
spring.datasource.password:MChaudhary@2025


spring.jpa.hibernate.ddl-auto:validate
spring.jpa.show-sql:true
spring.jpa.properties.hibernate.format_sql: true

spring.flyway.enabled:true
spring.flyway.locations:classpath:db/migration

server.port:8081

jwt.secret: S3cr3tK3yForPulseTradeJWTSign1ngThatIs32Byte
jwt.expiration: 3600000
